
# scanner/reporting/html.py
from jinja2 import Template
from datetime import datetime

TEMPLATE = Template("""
<!doctype html><html><head><meta charset="utf-8">
<title>OnyxIoT Scan Report</title>
<style>
body {
  font-family: system-ui, sans-serif;
  margin: 24px;
  background: #f9f9f9;
}
h1 { color: #222; }
.card {
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 12px;
  padding: 16px;
  margin: 12px 0;
  box-shadow: 0 1px 4px #0001;
}
.summary {
  background: #fff;
  border: 1px solid #ccc;
  border-radius: 10px;
  padding: 16px;
  margin-bottom: 20px;
  box-shadow: 0 1px 3px #0001;
}
.summary h2 {
  margin-top: 0;
}
.summary p {
  margin: 6px 0;
}
table {
  border-collapse: collapse;
  width: 100%;
  margin-top: 6px;
}
td, th {
  border: 1px solid #eee;
  padding: 6px;
  text-align: left;
  font-size: 14px;
}
pre {
  white-space: pre-wrap;
  word-wrap: break-word;
  font-size: 13px;
}
.sev-High { color: #b30000; }
.sev-Medium { color: #b36b00; }
.sev-Low { color: #007700; }
.info-line {
  margin: 4px 0;
  font-size: 14px;
}
footer {
  margin-top: 40px;
  font-size: 13px;
  color: #555;
  text-align: center;
}
</style></head><body>
<h1>OnyxIoT Scan Report</h1>

<div class="summary">
  <h2>Scan Summary</h2>
  <p><strong>Scan Date:</strong> {{ timestamp }}</p>
  {% if cidr %}
    <p><strong>Network Scanned:</strong> {{ cidr }}</p>
  {% endif %}
  <p><strong>Total Hosts:</strong> {{ hosts|length }}</p>
  <p><strong>Total Findings:</strong> {{ total_findings }}</p>
  <p>
    <strong>Severity Breakdown:</strong>
    High ({{ severity_counts["High"] }}),
    Medium ({{ severity_counts["Medium"] }}),
    Low ({{ severity_counts["Low"] }})
  </p>
</div>

{% for h in hosts %}
<div class="card">
  <h2>{{h.ip}}{% if h.hostname %} ({{h.hostname}}){% endif %}</h2>

  {% if h.vendor %}
    <div class="info-line"><strong>Vendor:</strong> {{h.vendor}}</div>
  {% endif %}
  <div class="info-line"><strong>MAC Address:</strong> {{h.mac or "?"}}</div>

  <h3>Services</h3>
  <table>
    <tr>
      <th>Port</th>
      <th>Name</th>
      <th>Banner</th>
      <th>TLS Info</th>
    </tr>

    {% for s in h.services %}
      <tr>
        <td>{{ s.port }}</td>
        <td>{{ s.name or "?" }}</td>
        <td><pre>{{ (s.banner or "")[:120] }}</pre></td>
        <td>
          {% if s.tls %}
            <strong>Protocol:</strong> {{ s.tls.protocol }}<br>
            {% if s.tls.notAfter %}
              <strong>Expires:</strong> {{ s.tls.notAfter }}<br>
            {% endif %}
            {% if s.tls.subject.CN %}
              <strong>CN:</strong> {{ s.tls.subject.CN }}
            {% endif %}
          {% else %}
            —
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </table>

  <h3>Findings</h3>
  {% if h.findings %}
    <ul>
    {% for f in h.findings %}
      <li class="sev-{{f.severity}}">
        <strong>[{{f.severity}}]</strong> {{f.title}} – {{f.description}}
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No findings for this host.</p>
  {% endif %}
</div>
{% endfor %}

<footer>
  <p>Generated by OnyxIoT – CYBR 4950: Cyber Capstone Project</p>
  <p>&copy; {{ year }} Devin Whitaker</p>
</footer>
</body></html>
""")

def write_html_report(hosts, out_path, cidr=None):
    """Render HTML report with summary section."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    severity_counts = {"High": 0, "Medium": 0, "Low": 0}
    total_findings = 0

    for h in hosts:
        for f in h.get("findings", []):
            total_findings += 1
            sev = f.get("severity", "Low")
            if sev in severity_counts:
                severity_counts[sev] += 1

    html = TEMPLATE.render(
        hosts=hosts,
        timestamp=timestamp,
        cidr=cidr,
        total_findings=total_findings,
        severity_counts=severity_counts,
        year=datetime.now().year
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)



